shared:
    image: node:12

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - step1:  sleep 5 && echo ok
            - step2:  sleep 5 && echo ok
            - shell: ./bin/myshell.sh -i -e ats
    fan1:
        requires: main
        steps:
            - step3:  sleep 5 && echo ok
            - step4:  sleep 5 && echo ok
            - step5:  sleep 5 && echo ok
            - step6:  sleep 5 && echo ok
            - step7:  sleep 5 && echo ok

    fan2:
        requires: main
        steps:
            - step8:  sleep 5 && echo ok
            - step9:  sleep 5 && echo ok
            - step10: sleep 5 && echo ok
            - step11: sleep 5 && echo ok
            - step12: sleep 5 && echo ok
    fan3:
        requires: main
        steps:
            - step13: sleep 5 && echo ok
            - step14: sleep 5 && echo ok
            - step15: sleep 5 && echo ok

    sink:
        requires: [fan1, fan2, fan3]
        steps:
            - step16: sleep 5 && echo ok
            - step17: sleep 5 && echo ok
            - step18: sleep 5 && echo ok
            - step19: sleep 5 && echo ok
            - step20: sleep 5 && echo ok
