shared:
    image: node:12

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - step1:  sleep 2 && echo ok
            - step2:  sleep 2 && echo ok
            - shell: ./bin/myshell.sh -i -e ats
    fan1:
        requires: main
        steps:
            - step3:  sleep 2 && echo ok
            - step4:  sleep 2 && echo ok
            - step5:  sleep 2 && echo ok
            - step6:  sleep 2 && echo ok
            - step7:  sleep 2 && echo ok
    fan2:
        requires: main
        steps:
            - step8:  sleep 2 && echo ok
            - step9:  sleep 2 && echo ok
            - step10: sleep 2 && echo ok
            - step11: sleep 2 && echo ok
            - step12: sleep 2 && echo ok
    # fan3:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan4:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan5:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan6:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan7:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan8:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan9:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    fan10:
        requires: main
        steps:
            - step13: sleep 2 && echo ok
            - step14: sleep 2 && echo ok
            - step15: sleep 2 && echo ok
    fan11:
        requires: main
        steps:
            - step13: sleep 2 && echo ok
            - step14: sleep 2 && echo ok
            - step15: sleep 2 && echo ok
    # fan12:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan13:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan14:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan15:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan16:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan17:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan18:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan19:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan20:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan21:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan22:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan23:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan24:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan25:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan26:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok
    # fan27:
    #     requires: main
    #     steps:
    #         - step13: sleep 2 && echo ok
    #         - step14: sleep 2 && echo ok
    #         - step15: sleep 2 && echo ok

    dot1:
        requires: [~fan1, ~fan2]
        steps:
            - step13: sleep 2 && echo ok

    # dot2:
    #     requires: [~fan1, ~fan2]
    #     steps:
    #         - step13: sleep 2 && echo ok

    # sink:
    #     requires: [dot1, dot2, fan3]
    #     steps:
    #         - step16: sleep 2 && echo ok
    #         - step17: sleep 2 && echo ok
    #         - step18: sleep 2 && echo ok
    #         - step19: sleep 2 && echo ok
    #         - step20: sleep 2 && echo ok
